Completed object manipulation 2.
mpowers1113/c1021-code-solutions pull request #59
Opened 2021-10-31 00:17 UTC by mpowers1113

![Screen Shot 2021-10-30 at 5 17 01 PM](https://user-images.githubusercontent.com/88848572/139561758-0fcfca55-fb1a-4cda-89ee-fb5bd2b75829.png)

2021-11-01 17:21 UTC, codingcodymiller requested changes

2021-11-01 17:21 UTC, codingcodymiller commented on object-manipulation-2/src/defaults.js
> +    newDefaultObj = target;
I don't think this line is necessary 🤔

2021-11-01 17:21 UTC, codingcodymiller commented on object-manipulation-2/src/defaults.js
> +  return newDefaultObj;
You should be able to just `return target`

2021-11-01 18:03 UTC, mpowers1113 commented
![Screen Shot 2021-11-01 at 11 03 29 AM](https://user-images.githubusercontent.com/88848572/139718857-a8553df8-6623-40c3-87cf-4ba34fb3662f.png)

2021-11-02 23:35 UTC, codingcodymiller approved these changes

2021-11-24 19:50 UTC, merged