Javascript carousel
mpowers1113/c1021-code-solutions pull request #68
Opened 2021-11-03 22:55 UTC by mpowers1113

![Kapture 2021-11-03 at 15 52 54](https://user-images.githubusercontent.com/88848572/140224674-d57f79b6-c3dd-481b-9589-f70275fa8ebc.gif)

2021-11-03 22:58 UTC, codingcodymiller requested changes
Nice work so far! One note to get you started:

2021-11-03 22:58 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  if (whichArrow === 'left' && currentImageArrayIndex === 0) {
I think you can vastly simplify this by breaking up the functionality for the arrows into two functions, one to move left, and one to move right.

2021-11-03 23:50 UTC, mpowers1113 commented
![Kapture 2021-11-03 at 16 48 28](https://user-images.githubusercontent.com/88848572/140234389-774d30f2-32ca-450a-b3fb-b5c930e6d6dc.gif)

2021-11-16 17:16 UTC, codingcodymiller approved these changes

2021-11-24 19:50 UTC, merged