Completed html-forms exercise.
mpowers1113/c1021-code-solutions pull request #7
Opened 2021-10-05 22:52 UTC by mpowers1113

2021-10-05 22:53 UTC, mpowers1113 commented
![Screen Shot 2021-10-05 at 3 53 32 PM](https://user-images.githubusercontent.com/88848572/136113663-1a42bec9-dd14-4d98-bdf8-b83385970af7.png)

2021-10-05 23:30 UTC, codingcodymiller requested changes
Great start here!! A few notes for you:

2021-10-05 23:30 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="email">Email</label>
This `label` isn't configured correctly, the value of the `for` attribute on a `label` should match the value of the `id` attribute on the form control element it is paired with.

2021-10-05 23:30 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="coding-is-cool">Why is coding cool?</label>
Same here, this is not configured correctly to pair with its form control element

2021-10-05 23:30 UTC, codingcodymiller commented on html-forms/index.html
> +        <label name="subscribe">Sign me up!</label>
Same here, this is not configured correctly to pair with its form control element

2021-10-05 23:30 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="comments">Comments</label>
Same here, this is not configured correctly to pair with its form control element

2021-10-06 00:11 UTC, mpowers1113 commented
![Screen Shot 2021-10-05 at 5 10 38 PM](https://user-images.githubusercontent.com/88848572/136120707-9b49abc2-9f15-415b-b1a4-69f0f92f9e34.png)

2021-10-06 00:17 UTC, mpowers1113 commented
reformatted with div's instead of paragraph elements
![Screen Shot 2021-10-05 at 5 16 58 PM](https://user-images.githubusercontent.com/88848572/136121151-3e4dd345-abb9-47aa-ba9e-bd34fc39b95a.png)

2021-10-06 16:10 UTC, codingcodymiller approved these changes

2021-10-06 17:34 UTC, merged