Completed express get json exercise.
mpowers1113/c1021-code-solutions pull request #90
Opened 2021-12-01 01:48 UTC by mpowers1113

![Screen Shot 2021-11-30 at 5 46 11 PM](https://user-images.githubusercontent.com/88848572/144157009-97597765-10a7-4f64-89c1-7621d63cb7e0.png)

2021-12-01 01:55 UTC, thebearingedge requested changes

2021-12-01 01:55 UTC, thebearingedge commented on express-get-json/index.js
> +}
Try doing this in your route so that if the data model changes you don't have to manage this array too.

2021-12-01 01:58 UTC, mpowers1113 commented
![Screen Shot 2021-11-30 at 5 58 31 PM](https://user-images.githubusercontent.com/88848572/144157958-3de13ef0-0c65-435c-a783-591f244f4acf.png)

2021-12-02 23:06 UTC, thebearingedge approved these changes

2021-12-02 23:07 UTC, merged